### ISSUE TITLE
Deploy a cron job on dandi@drogon to update the "validation"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-datasets#10]
Since we need to access all data, we can't have a github workflow for it, and I do not want to expose drogon as a github worker.  So I think we should just have a cron job which runs e.g. 10 minutes (with `flock -E 0 -e...` as other jobs do to not overlap) and does in its dedicated environment/setup

- update `dandi-cli` (from master), `pywnb` and `hdmf` from 
- run the validation script
- record versions of the above modules in a `datalad save` message committing all the changes
- push here (if anything changed)

Extra features
- along the lines of https://github.com/dandi/dandi-api-datasets/pull/6#issuecomment-778704578 provide top level `SUMMARY.md` (or alike) which would state 
  - the number of dandisets with any particular validation issue
  - dandisets which have some assets and have no validation errors of any kind
- note that this portion of the script (or just a separate one) should consider all dandisets and not only the ones provided on cli.

this way whenever we update schema or fix anything we could see that reflected.

**Comment by jwodder** [comment]
@yarikoptic By "the validation script," you mean `populate_dandiset_asset_yamls.py`?  That takes about 17 hours to run on everything.   (I think the biggest culprit might be the calculation of the file digests.)  Running every 10 minutes, even with flock, seems excessive.

> update dandi-cli (from master), pywnb and hdmf from

Did you mean to finish that sentence?

Also, should this cronjob run under my account?  I don't have permission to push directly to this repository.

**Comment by yarikoptic** [comment]
yikes.  I expect (with all the caching of reading metadata etc) it to complete much faster if no changes to `dandi-cli` or any other dependencies, and only some dandisets to update.  Since drogon is generally not CPU busy, I am ok for it to get tortured a bit even in excess ;)  I would set cron job to the duration it takes to do "warm" run (right after a run) which should be relatively fast.
It might even add some multiprocessing (or may be even multithread might be enough to gain speed up) parallelization across dandisets?

**Comment by jwodder** [comment]
@yarikoptic Whose user and GitHub accounts should the cronjob run under?  Note that my GitHub account currently does not have permission to push to this repository.

**Comment by yarikoptic** [comment]
we already push updates to dandisets from `dandi@` on drogon.  It has its git config setup already with the token and ssh key which I hope should be good enough since works for https://github.com/dandi/dandisets/ and I do not see a dedicated deploy key there

**Comment by jwodder** [comment]
@yarikoptic I just ran an initial draft of the script, and it took almost 25 hours.

**Comment by jwodder** [comment]
@yarikoptic A second run, started right after the first, took just under 16 hours, though the script failed after running `populate_dandiset_assets_yamls.py` due to a bad Git command.

**Comment by yarikoptic** [comment]
what bad Git command?
I guess let's set it on daily basis, I will look into what/why it is taking this long later on

**Comment by jwodder** [comment]
@yarikoptic In order to handle any changes to the Git repository that may happen while the script is running, I added in `git pull --autostash` between invoking the `.py` script and committing the results, but I was consulting the manpages for the Git version on my laptop when I did that, and it turns out the older Git on drogo requires `--rebase` in order for `--autostash` to work.  It's fixed now; don't worry about it.

**Comment by jwodder** [comment]
@yarikoptic OK, I've set [this script](https://github.com/dandi/dandi-api-datasets/blob/master/tools/validate-all.sh) to run every day at midnight.

**Comment by yarikoptic** [comment]
ok, let's mark this one resolved and anything else would go into new issues. Thank you @jwodder!
