### ISSUE TITLE
NF: populate_dandiset_asset_yamls.py

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-datasets#3]
Following weekly meetup discussion: to ensure correct extraction of metadata records across dandisets' assets, it would be useful to populate this repository with dandisets' assets metadata.

- just do on drogon where we have `dandisets/` fully populated
- for a given dandiset (like in `populate_dandiset_yaml.py`) 
  - go through all of its files/assets
  - extract/convert metadata identically to how `dandi upload` does it
  - save as `<asset_path>.yaml`

**Comment by jwodder** [comment]
@yarikoptic Should the script and/or new files be committed to the repository or just left lying there?  Should the output files be placed under `dandisets/` next to the assets themselves or in the top-level dandiset directories?

**Comment by yarikoptic** [comment]
Just populated, I can commit with outside datalad run, add I do for the other script

**Comment by jwodder** [comment]
@yarikoptic 

* How should non-NWB assets be handled?
* To be clear: The directory on drogon where this script is to be run is `/mnt/backup/dandi/dandisets/`, correct?  Are you telling me to run it there just for testing purposes, or do you just want me to run the script there once and leave the resulting files behind, or do you not want me to actually run it there and you're planning on running the script there yourself later?
* I don't have permission to write to `/mnt/backup/dandi/dandisets/` on drogon.

**Comment by yarikoptic** [comment]
> * How should non-NWB assets be handled?

all generic fields (contentSize, encodingFormat, digest, path) should be populated.

> To be clear: ...

Do on drogon smth like

```
dandi@drogon:/tmp$ git clone https://github.com/dandi/dandi-api-datasets
...
dandi@drogon:/tmp$ cd dandi-api-datasets/
dandi@drogon:/tmp/dandi-api-datasets$ rmdir dandisets
dandi@drogon:/tmp/dandi-api-datasets$ ln -s /mnt/backup/dandi/dandisets .
```
so you have all of them available and can run your script to populate metadata files in this repo (just to make sure everything works etc).  I will later do the final run, most likely by first installing that `subdatasets` in "wreckless" mode or actually we could just rely on CoW of the file system there.  I thought to do it right away but it seems even with CoW it is a bit "straining" ;)

> I don't have permission to write to /mnt/backup/dandi/dandisets/ on drogon.

you should not write into them -- they are under "cron job" control.  Result metadata dumps will go into this (https://github.com/dandi/dandi-api-datasets) repo, not original dandisets.

This is primarily an exercise to verify that dandi-cli logic for getting assets metadata is not crashing + get an easy to access/review dumps of that metadata (within this repo).

**Comment by jwodder** [comment]
@yarikoptic 

> all generic fields (contentSize, encodingFormat, digest, path) should be populated.

Not even dandi-cli's `upload()` populates `encodingFormat` for non-NWB files.  That's currently marked in the code as "TODO".

Also, `path` in metadata is currently not set by `upload()` for any files.

**Comment by yarikoptic** [comment]
> Not even dandi-cli's `upload()` populates `encodingFormat` for non-NWB files. That's currently marked in the code as "TODO".

I guess we could keep it TODO for this round

> Also, path in metadata is currently not set by upload() for any files.

hm, I think we should upload it hence https://github.com/dandi/dandi-api/issues/91 but also see https://github.com/dandi/dandi-api/issues/92 .
